-- MySQL Script generated by MySQL Workbench
-- Sat Aug 17 22:04:53 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema alfarorecinosayalavillatororamos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema alfarorecinosayalavillatororamos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `alfarorecinosayalavillatororamos` DEFAULT CHARACTER SET utf8 ;
USE `alfarorecinosayalavillatororamos` ;

-- -----------------------------------------------------
-- Table `alfarorecinosayalavillatororamos`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alfarorecinosayalavillatororamos`.`facultad` (
  `codigoFacultad` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`codigoFacultad`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `alfarorecinosayalavillatororamos`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alfarorecinosayalavillatororamos`.`carrera` (
  `codigoCarrera` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `cantidadMaterias` INT(11) NULL DEFAULT NULL,
  `codigoFacultad` INT(11) NOT NULL,
  PRIMARY KEY (`codigoCarrera`),
  INDEX `fk_carrera_facultad_idx` (`codigoFacultad` ASC),
  CONSTRAINT `fk_carrera_facultad`
    FOREIGN KEY (`codigoFacultad`)
    REFERENCES `alfarorecinosayalavillatororamos`.`facultad` (`codigoFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `alfarorecinosayalavillatororamos`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alfarorecinosayalavillatororamos`.`estudiante` (
  `codigoEstudiante` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `edad` INT(11) NULL DEFAULT NULL,
  `genero` VARCHAR(50) NULL DEFAULT NULL,
  `cum` DOUBLE NULL DEFAULT NULL,
  `intereses` VARCHAR(75) NULL DEFAULT NULL,
  `codigoCarrera` INT(11) NOT NULL,
  PRIMARY KEY (`codigoEstudiante`),
  INDEX `fk_estudiante_carrera_idx` (`codigoCarrera` ASC),
  CONSTRAINT `fk_estudiante_carrera`
    FOREIGN KEY (`codigoCarrera`)
    REFERENCES `alfarorecinosayalavillatororamos`.`carrera` (`codigoCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `alfarorecinosayalavillatororamos`.`tipousuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alfarorecinosayalavillatororamos`.`tipousuario` (
  `codigoTipo` INT(11) NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL DEFAULT NULL,
  PRIMARY KEY (`codigoTipo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `alfarorecinosayalavillatororamos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `alfarorecinosayalavillatororamos`.`usuario` (
  `codigoUsuario` INT(11) NOT NULL,
  `usuario` VARCHAR(30) NULL DEFAULT NULL,
  `contra` VARCHAR(30) NULL DEFAULT NULL,
  `nombre` VARCHAR(30) NULL DEFAULT NULL,
  `apellido` VARCHAR(30) NULL DEFAULT NULL,
  `edad` INT(11) NULL DEFAULT NULL,
  `codigoTipo` INT(11) NOT NULL,
  PRIMARY KEY (`codigoUsuario`),
  INDEX `fk_usuario_tipoUsuario_idx` (`codigoTipo` ASC),
  CONSTRAINT `fk_usuario_tipoUsuario`
    FOREIGN KEY (`codigoTipo`)
    REFERENCES `alfarorecinosayalavillatororamos`.`tipousuario` (`codigoTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

alter table usuario alter column codigoUsuario SET INT(11) NOT NULL AUTO_INCREMENT;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
