-- MySQL Script generated by MySQL Workbench
-- Sat Aug 17 07:59:33 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AlfaroRecinosAyalaVillatoroRamos
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AlfaroRecinosAyalaVillatoroRamos
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AlfaroRecinosAyalaVillatoroRamos` DEFAULT CHARACTER SET utf8 ;
USE `AlfaroRecinosAyalaVillatoroRamos` ;
-- -----------------------------------------------------
-- Table `AlfaroRecinosAyalaVillatoroRamos`.`facultad`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlfaroRecinosAyalaVillatoroRamos`.`facultad` (
  `codigoFacultad` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `telefono` VARCHAR(20) NULL,
  PRIMARY KEY (`codigoFacultad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlfaroRecinosAyalaVillatoroRamos`.`carrera`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlfaroRecinosAyalaVillatoroRamos`.`carrera` (
  `codigoCarrera` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `cantidadMaterias` INT NULL,
  `codigoFacultad` INT NOT NULL,
  PRIMARY KEY (`codigoCarrera`),
  INDEX `fk_carrera_facultad_idx` (`codigoFacultad` ASC),
  CONSTRAINT `fk_carrera_facultad`
    FOREIGN KEY (`codigoFacultad`)
    REFERENCES `AlfaroRecinosAyalaVillatoroRamos`.`facultad` (`codigoFacultad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlfaroRecinosAyalaVillatoroRamos`.`tipoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlfaroRecinosAyalaVillatoroRamos`.`tipoUsuario` (
  `codigoTipo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(30) NULL,
  PRIMARY KEY (`codigoTipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlfaroRecinosAyalaVillatoroRamos`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlfaroRecinosAyalaVillatoroRamos`.`usuario` (
  `codigoUsuario` INT NOT NULL,
  `usuario` VARCHAR(30) NULL,
  `contra` VARCHAR(30) NULL,
  `nombre` VARCHAR(30) NULL,
  `apellido` VARCHAR(30) NULL,
  `edad` INT NULL,
  `codigoTipo` INT NOT NULL,
  PRIMARY KEY (`codigoUsuario`),
  INDEX `fk_usuario_tipoUsuario_idx` (`codigoTipo` ASC),
  CONSTRAINT `fk_usuario_tipoUsuario`
    FOREIGN KEY (`codigoTipo`)
    REFERENCES `AlfaroRecinosAyalaVillatoroRamos`.`tipoUsuario` (`codigoTipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)    
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AlfaroRecinosAyalaVillatoroRamos`.`estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlfaroRecinosAyalaVillatoroRamos`.`estudiante` (
  `codigoEstudiante` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `edad` INT NULL,
  `genero` VARCHAR(50) NULL,
  `cum` DOUBLE NULL,
  `intereses` VARCHAR(75) NULL,
  `codigoCarrera` INT NOT NULL,
  `codigoUsuario` INT NOT NULL,
  PRIMARY KEY (`codigoEstudiante`),
  INDEX `fk_estudiante_carrera_idx` (`codigoCarrera` ASC),
  INDEX `fk_usuario_estudiante_idx` (`codigoUsuario` ASC),
  CONSTRAINT `fk_estudiante_carrera`
    FOREIGN KEY (`codigoCarrera`)
    REFERENCES `AlfaroRecinosAyalaVillatoroRamos`.`carrera` (`codigoCarrera`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;