package com.Vistas;
import com.Dao.DaoCarrera;
import com.Entidades.Validar;
import com.LogicaNegocio.*;

/**
 * nombre de la clase: mdi_Principal 
 * version:1.0
 * fecha: 17/08/19
 * copyright:ITCA-FEPADE
 * @author Brenda Ramos
 */
public class mdi_Principal extends javax.swing.JFrame {
    
    TsCarrera tCarrera = new TsCarrera();
    TsEstudiante tEstudiante=new TsEstudiante();
    TsFacultad tFacultad=new TsFacultad();
    TsTipoUsuario tTipo=new TsTipoUsuario();
    TsUsuario tUsuario=new TsUsuario();
    
    void llenarFacultad()
    {
        tableFacultad.setModel(tFacultad.datos());
    }
    
    void llenarCarrera()
    {
        tableCarrera.setModel(tCarrera.datos());
        //
    }
    
    void llenarEstudiante()
    {
        tablaEstudiante.setModel(tEstudiante.datos());
    }
    
    void llenarUsuario()
    {
        tableUser.setModel(tUsuario.datos());
    }
    
    Validar v= new Validar();
    public mdi_Principal() {
        initComponents();
        this.setExtendedState(mdi_Principal.MAXIMIZED_BOTH);
        ///validacion de cajas de texto de solo letras
        v.validarNombres(txtApellido);
        v.validarNombres(txtNomCarre);
        v.validarNombres(txtinteres);
        v.validarNombres(txtnombrefacu);
        v.validarNombres(txtnombre);
        v.validarUsuario(txtnomUser);
        //validaciode  cajas de texto de solo nuemros 
        v.validarCUM(txtcum);
        v.validarumeros(txtCodUser);
        v.validarumeros(txtCodigo);
        v.validarumeros(txtcodigfacu);
        v.validarumeros(txttelefacu);
        v.validarumeros(txtcodigo);
    }
    void limpiar()
    {
        txtApellido.setText("");
        txtCodUser.setText("");
        txtCodigo.setText("");
        txtNomCarre.setText("");
        txtUser.setText("");
        txtcodigfacu.setText("");
        txtcodigo.setText("");
        txtcum.setText("");
        txtinteres.setText("");
        txtnombre.setText("");
        txtnomUser.setText("");
        txtnombrefacu.setText("");
        txttelefacu.setText("");
        cmbFacultad.setSelectedIndex(0);
        cmbTipoUSer.setSelectedIndex(0);
        cmbcarrera.setSelectedIndex(0);
        passwordUser.setText("");
        //spinerEdad.setModel(null);
        //spinnerEdadUser.setModel(null);
        //spinnerMaterias.setModel(null);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        desktopPane = new javax.swing.JDesktopPane();
        internalEstudiante = new javax.swing.JInternalFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtcodigo = new javax.swing.JTextField();
        txtnombre = new javax.swing.JTextField();
        txtcum = new javax.swing.JTextField();
        txtinteres = new javax.swing.JTextField();
        cmbcarrera = new javax.swing.JComboBox<>();
        rbmasculino = new javax.swing.JRadioButton();
        spinerEdad = new javax.swing.JSpinner();
        btnagregarEstu = new javax.swing.JButton();
        btnmodific = new javax.swing.JButton();
        btneliminar = new javax.swing.JButton();
        btnlimpiar = new javax.swing.JButton();
        rbfemenino = new javax.swing.JRadioButton();
        btnExit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaEstudiante = new javax.swing.JTable();
        internalFacultad = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtnombrefacu = new javax.swing.JTextField();
        txtcodigfacu = new javax.swing.JTextField();
        btnAgreFac = new javax.swing.JButton();
        btnModFacu = new javax.swing.JButton();
        btnEliFacu = new javax.swing.JButton();
        btnLimFac = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        txttelefacu = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableFacultad = new javax.swing.JTable();
        internalCarrera = new javax.swing.JInternalFrame();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableCarrera = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbFacultad = new javax.swing.JComboBox<>();
        txtCodigo = new javax.swing.JTextField();
        txtNomCarre = new javax.swing.JTextField();
        spinnerMaterias = new javax.swing.JSpinner();
        btnElim = new javax.swing.JButton();
        btnModif = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnLimp = new javax.swing.JButton();
        btnExitCarr = new javax.swing.JButton();
        internalUser = new javax.swing.JInternalFrame();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableUser = new javax.swing.JTable();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtCodUser = new javax.swing.JTextField();
        txtnomUser = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        passwordUser = new javax.swing.JPasswordField();
        cmbTipoUSer = new javax.swing.JComboBox<>();
        txtUser = new javax.swing.JTextField();
        spinnerEdadUser = new javax.swing.JSpinner();
        btAgreuser = new javax.swing.JButton();
        btnModUser = new javax.swing.JButton();
        btnElimUser = new javax.swing.JButton();
        btnLimUser = new javax.swing.JButton();
        btnSalirUser = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        usuMenu = new javax.swing.JMenu();
        newUsuMenuItem = new javax.swing.JMenuItem();
        facuMenu = new javax.swing.JMenu();
        newFacuMenuItem = new javax.swing.JMenuItem();
        carreMenu = new javax.swing.JMenu();
        newCarrMenuItem = new javax.swing.JMenuItem();
        estuMenu = new javax.swing.JMenu();
        newEstMenuItem = new javax.swing.JMenuItem();
        repoMenu = new javax.swing.JMenu();
        salirMenu = new javax.swing.JMenu();
        exitMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setName(""); // NOI18N

        internalEstudiante.setVisible(true);

        jLabel1.setText("Datos Estudiante");

        jLabel2.setText("Codigo");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Edad");

        jLabel5.setText("Carrera");

        jLabel6.setText("Genero");

        jLabel7.setText("Cum");

        jLabel8.setText("Intereses:");

        txtcodigo.setEnabled(false);

        txtnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombreActionPerformed(evt);
            }
        });
        txtnombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreKeyTyped(evt);
            }
        });

        buttonGroup1.add(rbmasculino);
        rbmasculino.setText("Masculino");

        spinerEdad.setModel(new javax.swing.SpinnerNumberModel(15, 15, 100, 1));

        btnagregarEstu.setText("Agregar");
        btnagregarEstu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarEstuActionPerformed(evt);
            }
        });

        btnmodific.setText("Modificar");

        btneliminar.setText("Eliminar");

        btnlimpiar.setText("Limpiar");
        btnlimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiarActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbfemenino);
        rbfemenino.setText("Femenino");

        btnExit.setText("Salir");
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(spinerEdad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                                        .addComponent(txtcum, javax.swing.GroupLayout.Alignment.LEADING))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnagregarEstu)
                                .addGap(29, 29, 29)
                                .addComponent(btnmodific)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtinteres))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(18, 18, 18)
                                        .addComponent(cmbcarrera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addComponent(rbfemenino)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rbmasculino))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btneliminar)
                                .addGap(34, 34, 34)
                                .addComponent(btnlimpiar)
                                .addGap(31, 31, 31)
                                .addComponent(btnExit))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1)
                                .addGap(201, 201, 201)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtcodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(txtnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbmasculino)
                    .addComponent(rbfemenino))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel8)
                    .addComponent(txtinteres, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinerEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(txtcum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbcarrera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregarEstu)
                    .addComponent(btnmodific)
                    .addComponent(btneliminar)
                    .addComponent(btnlimpiar)
                    .addComponent(btnExit))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tablaEstudiante.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablaEstudiante);

        javax.swing.GroupLayout internalEstudianteLayout = new javax.swing.GroupLayout(internalEstudiante.getContentPane());
        internalEstudiante.getContentPane().setLayout(internalEstudianteLayout);
        internalEstudianteLayout.setHorizontalGroup(
            internalEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(internalEstudianteLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        internalEstudianteLayout.setVerticalGroup(
            internalEstudianteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalEstudianteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                .addContainerGap())
        );

        desktopPane.add(internalEstudiante);
        internalEstudiante.setBounds(10, 10, 700, 500);

        internalFacultad.setVisible(false);

        jLabel9.setText("REGISTRO DE FACULTADES");

        jLabel10.setText("Codigo:");

        jLabel11.setText("Nombre:");

        jLabel12.setText("Telefono");

        txtnombrefacu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnombrefacuActionPerformed(evt);
            }
        });

        txtcodigfacu.setEnabled(false);

        btnAgreFac.setText("Agregar");

        btnModFacu.setText("Modificar");

        btnEliFacu.setText("Eliminar");

        btnLimFac.setText("Limpiar");
        btnLimFac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimFacActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        try {
            txttelefacu.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnombrefacu, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtcodigfacu, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addGap(18, 18, 18)
                                .addComponent(txttelefacu, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(49, 49, 49)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnAgreFac)
                                    .addComponent(btnEliFacu))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnModFacu)
                                    .addComponent(btnLimFac)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(99, 99, 99)
                                .addComponent(btnSalir))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel9)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtcodigfacu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgreFac)
                    .addComponent(btnModFacu))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtnombrefacu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliFacu)
                            .addComponent(btnLimFac))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(btnSalir)
                        .addContainerGap(25, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txttelefacu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        tableFacultad.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(tableFacultad);

        javax.swing.GroupLayout internalFacultadLayout = new javax.swing.GroupLayout(internalFacultad.getContentPane());
        internalFacultad.getContentPane().setLayout(internalFacultadLayout);
        internalFacultadLayout.setHorizontalGroup(
            internalFacultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalFacultadLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(58, Short.MAX_VALUE))
            .addGroup(internalFacultadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        internalFacultadLayout.setVerticalGroup(
            internalFacultadLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalFacultadLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(internalFacultad);
        internalFacultad.setBounds(10, 10, 600, 430);

        internalCarrera.setVisible(false);

        tableCarrera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(tableCarrera);

        jLabel13.setText("REGISTRO DE CARRERA");

        jLabel14.setText("Codigo");

        jLabel15.setText("Nombre");

        jLabel16.setText("Cantidad Materia");

        jLabel17.setText("Facultad");

        txtCodigo.setEnabled(false);

        spinnerMaterias.setModel(new javax.swing.SpinnerNumberModel(1, 1, 60, 1));

        btnElim.setText("Eliminar");

        btnModif.setText("Modificar");

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnLimp.setText("Limpiar");
        btnLimp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpActionPerformed(evt);
            }
        });

        btnExitCarr.setText("Salir");
        btnExitCarr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitCarrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(18, 18, 18)
                        .addComponent(txtNomCarre))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(18, 18, 18)
                        .addComponent(txtCodigo))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(spinnerMaterias))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(cmbFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnElim)
                                .addGap(22, 22, 22)
                                .addComponent(btnLimp))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnAgregar)
                                .addGap(18, 18, 18)
                                .addComponent(btnModif))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExitCarr)
                        .addGap(53, 53, 53)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(152, 152, 152))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(txtNomCarre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(spinnerMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAgregar)
                            .addComponent(btnModif))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnElim)
                            .addComponent(btnLimp))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(cmbFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnExitCarr))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout internalCarreraLayout = new javax.swing.GroupLayout(internalCarrera.getContentPane());
        internalCarrera.getContentPane().setLayout(internalCarreraLayout);
        internalCarreraLayout.setHorizontalGroup(
            internalCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, internalCarreraLayout.createSequentialGroup()
                .addContainerGap(101, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, internalCarreraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        internalCarreraLayout.setVerticalGroup(
            internalCarreraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, internalCarreraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(internalCarrera);
        internalCarrera.setBounds(40, 20, 630, 460);

        internalUser.setVisible(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 214, Short.MAX_VALUE)
        );

        tableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tableUser);

        jLabel18.setText("Registro Usuario");

        jLabel19.setText("Codigo");

        jLabel20.setText("Nombre:");

        jLabel21.setText("Edad");

        jLabel23.setText("Apellido");

        jLabel24.setText("Tipo de Usuario");

        jLabel25.setText("Usuario");

        jLabel26.setText("Cotraseña");

        spinnerEdadUser.setModel(new javax.swing.SpinnerNumberModel(15, 15, 100, 1));

        btAgreuser.setText("Agregar");

        btnModUser.setText("Modificar");

        btnElimUser.setText("Eliminar");

        btnLimUser.setText("Limpiar");
        btnLimUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimUserActionPerformed(evt);
            }
        });

        btnSalirUser.setText("Salir");
        btnSalirUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout internalUserLayout = new javax.swing.GroupLayout(internalUser.getContentPane());
        internalUser.getContentPane().setLayout(internalUserLayout);
        internalUserLayout.setHorizontalGroup(
            internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalUserLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(internalUserLayout.createSequentialGroup()
                        .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(internalUserLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(txtCodUser))
                            .addGroup(internalUserLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtnomUser, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(internalUserLayout.createSequentialGroup()
                                .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25)
                                    .addComponent(jLabel21))
                                .addGap(15, 15, 15)
                                .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(spinnerEdadUser, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                                    .addComponent(txtUser))))
                        .addGap(30, 30, 30)
                        .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtApellido)
                            .addComponent(cmbTipoUSer, 0, 119, Short.MAX_VALUE)
                            .addComponent(passwordUser))
                        .addGap(73, 73, 73))
                    .addGroup(internalUserLayout.createSequentialGroup()
                        .addComponent(btAgreuser)
                        .addGap(18, 18, 18)
                        .addComponent(btnModUser)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addGroup(internalUserLayout.createSequentialGroup()
                                .addComponent(btnElimUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnLimUser)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnSalirUser)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(internalUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addContainerGap())
        );
        internalUserLayout.setVerticalGroup(
            internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(internalUserLayout.createSequentialGroup()
                .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(internalUserLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel18)
                        .addGap(12, 12, 12)
                        .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(txtCodUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel20)
                            .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel23)
                                .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtnomUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(14, 14, 14)
                        .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(internalUserLayout.createSequentialGroup()
                                .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel21)
                                        .addComponent(spinnerEdadUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel24)
                                        .addComponent(cmbTipoUSer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel25)
                                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel26)))
                            .addComponent(passwordUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(internalUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btAgreuser)
                            .addComponent(btnModUser)
                            .addComponent(btnElimUser)
                            .addComponent(btnLimUser)
                            .addComponent(btnSalirUser))))
                .addGap(15, 15, 15)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        desktopPane.add(internalUser);
        internalUser.setBounds(50, 20, 610, 480);

        usuMenu.setMnemonic('f');
        usuMenu.setText("Usuarios");

        newUsuMenuItem.setMnemonic('o');
        newUsuMenuItem.setText("Agregar Usuario");
        newUsuMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newUsuMenuItemActionPerformed(evt);
            }
        });
        usuMenu.add(newUsuMenuItem);

        menuBar.add(usuMenu);

        facuMenu.setMnemonic('h');
        facuMenu.setText("Facultad");

        newFacuMenuItem.setMnemonic('c');
        newFacuMenuItem.setText("Agregar Facultad");
        newFacuMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFacuMenuItemActionPerformed(evt);
            }
        });
        facuMenu.add(newFacuMenuItem);

        menuBar.add(facuMenu);

        carreMenu.setText("Carrera");

        newCarrMenuItem.setText("Agregar Carrera");
        newCarrMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCarrMenuItemActionPerformed(evt);
            }
        });
        carreMenu.add(newCarrMenuItem);

        menuBar.add(carreMenu);

        estuMenu.setMnemonic('e');
        estuMenu.setText("Estudiantes");

        newEstMenuItem.setMnemonic('t');
        newEstMenuItem.setText("Agregar Estudiante");
        newEstMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newEstMenuItemActionPerformed(evt);
            }
        });
        estuMenu.add(newEstMenuItem);

        menuBar.add(estuMenu);

        repoMenu.setText("Reportes");
        menuBar.add(repoMenu);

        salirMenu.setText("Salir");

        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        salirMenu.add(exitMenuItem);

        menuBar.add(salirMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 522, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//mostrar formulario estudiante
    private void newEstMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newEstMenuItemActionPerformed
        internalEstudiante.setVisible(true);
        llenarEstudiante();        
        facuMenu.setEnabled(false);
        carreMenu.setEnabled(false);
        usuMenu.setEnabled(false);
        repoMenu.setEnabled(false);
    }//GEN-LAST:event_newEstMenuItemActionPerformed
//salir del formulario estidamte
    private void btnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseClicked
        internalEstudiante.setVisible(false);
        usuMenu.setEnabled(true);
        facuMenu.setEnabled(true);
        carreMenu.setEnabled(true);
        repoMenu.setEnabled(true);
    }//GEN-LAST:event_btnExitMouseClicked
//salir de formulario facultad
    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        internalFacultad.setVisible(false);
        usuMenu.setEnabled(true);
        carreMenu.setEnabled(true);
        repoMenu.setEnabled(true);
        estuMenu.setEnabled(true);
    }//GEN-LAST:event_btnSalirActionPerformed
//mostrar formulario de facultad
    private void newFacuMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFacuMenuItemActionPerformed
        internalFacultad.setVisible(true);
        llenarFacultad();
        carreMenu.setEnabled(false);
        usuMenu.setEnabled(false);
        repoMenu.setEnabled(false);
        estuMenu.setEnabled(false);
    }//GEN-LAST:event_newFacuMenuItemActionPerformed
//boton salir del todo el mdi
    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed
//mostrar formulario de carreras 
    private void newCarrMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCarrMenuItemActionPerformed
        internalCarrera.setVisible(true);
        llenarCarrera();
        facuMenu.setEnabled(false);
        usuMenu.setEnabled(false);
        repoMenu.setEnabled(false);
        estuMenu.setEnabled(false);
        
    }//GEN-LAST:event_newCarrMenuItemActionPerformed
//salir del formulario carrera
    private void btnExitCarrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitCarrActionPerformed
        internalCarrera.setVisible(false);
        
        usuMenu.setEnabled(true);
        facuMenu.setEnabled(true);
        repoMenu.setEnabled(true);
        estuMenu.setEnabled(true);
    }//GEN-LAST:event_btnExitCarrActionPerformed
//salir del formulario usuario
    private void btnSalirUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirUserActionPerformed
        internalUser.setVisible(false);
        usuMenu.setEnabled(true);
        facuMenu.setEnabled(true);
        carreMenu.setEnabled(true);
        repoMenu.setEnabled(true);
        estuMenu.setEnabled(true);
    }//GEN-LAST:event_btnSalirUserActionPerformed
//mostrar formulario agregar ususario
    private void newUsuMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newUsuMenuItemActionPerformed
        internalUser.setVisible(true);
        llenarUsuario();
        facuMenu.setEnabled(false);
        carreMenu.setEnabled(false);
        repoMenu.setEnabled(false);
        estuMenu.setEnabled(false);
    }//GEN-LAST:event_newUsuMenuItemActionPerformed
//metodo limpiar de formulario Estudiate
    private void btnlimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiarActionPerformed
        limpiar();
    }//GEN-LAST:event_btnlimpiarActionPerformed
//limpiar de facultades
    private void btnLimFacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimFacActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimFacActionPerformed
///limpiar del formulario carrera
    private void btnLimpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimpActionPerformed
///limpiar del formulario user
    private void btnLimUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimUserActionPerformed
        limpiar();
    }//GEN-LAST:event_btnLimUserActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnagregarEstuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarEstuActionPerformed
        tEstudiante.agregar(txtnombre.getText(), spinerEdad.getValue().
                toString(), buttonGroup1.getSelection().toString(),
                txtcum.getText(), txtinteres.getText(),
                cmbcarrera.getSelectedItem().toString());
    }//GEN-LAST:event_btnagregarEstuActionPerformed

    private void txtnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnombreActionPerformed

    private void txtnombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreKeyTyped
        
    }//GEN-LAST:event_txtnombreKeyTyped

    private void txtnombrefacuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnombrefacuActionPerformed
   // TODO add your handling code here:
    }//GEN-LAST:event_txtnombrefacuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdi_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdi_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdi_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdi_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdi_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAgreuser;
    private javax.swing.JButton btnAgreFac;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliFacu;
    private javax.swing.JButton btnElim;
    private javax.swing.JButton btnElimUser;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnExitCarr;
    private javax.swing.JButton btnLimFac;
    private javax.swing.JButton btnLimUser;
    private javax.swing.JButton btnLimp;
    private javax.swing.JButton btnModFacu;
    private javax.swing.JButton btnModUser;
    private javax.swing.JButton btnModif;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSalirUser;
    private javax.swing.JButton btnagregarEstu;
    private javax.swing.JButton btneliminar;
    private javax.swing.JButton btnlimpiar;
    private javax.swing.JButton btnmodific;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JMenu carreMenu;
    private javax.swing.JComboBox<String> cmbFacultad;
    private javax.swing.JComboBox<String> cmbTipoUSer;
    private javax.swing.JComboBox<String> cmbcarrera;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenu estuMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu facuMenu;
    private javax.swing.JInternalFrame internalCarrera;
    private javax.swing.JInternalFrame internalEstudiante;
    private javax.swing.JInternalFrame internalFacultad;
    private javax.swing.JInternalFrame internalUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newCarrMenuItem;
    private javax.swing.JMenuItem newEstMenuItem;
    private javax.swing.JMenuItem newFacuMenuItem;
    private javax.swing.JMenuItem newUsuMenuItem;
    private javax.swing.JPasswordField passwordUser;
    private javax.swing.JRadioButton rbfemenino;
    private javax.swing.JRadioButton rbmasculino;
    private javax.swing.JMenu repoMenu;
    private javax.swing.JMenu salirMenu;
    private javax.swing.JSpinner spinerEdad;
    private javax.swing.JSpinner spinnerEdadUser;
    private javax.swing.JSpinner spinnerMaterias;
    private javax.swing.JTable tablaEstudiante;
    private javax.swing.JTable tableCarrera;
    private javax.swing.JTable tableFacultad;
    private javax.swing.JTable tableUser;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtCodUser;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNomCarre;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtcodigfacu;
    private javax.swing.JTextField txtcodigo;
    private javax.swing.JTextField txtcum;
    private javax.swing.JTextField txtinteres;
    private javax.swing.JTextField txtnomUser;
    private javax.swing.JTextField txtnombre;
    private javax.swing.JTextField txtnombrefacu;
    private javax.swing.JFormattedTextField txttelefacu;
    private javax.swing.JMenu usuMenu;
    // End of variables declaration//GEN-END:variables

}
